### ISSUE TITLE
Pier copy/cp subcommand

### ISSUE THREAD

**Issue by Plommonsorbet** [pier-cli/pier#45]
## Example usage
`pier copy <original> <new>`
with the alias:
`pier cp <original> <new>`

### Warnings
The subcommand should not allow you to write over an existing script, but we could perhaps add a `-f` / `--force` flag. This is something that could be useful for the add command as well.

**Comment by yhung119** [comment]
hey :)) i'm interested on helping this one. I have some implementation locally to review but unable to push. I'm getting a 403 error code.
Any idea on how to fix this? Thanks.
