### ISSUE TITLE
Config file generation

### ISSUE THREAD

**Issue by niniack** [pier-cli/pier#59]
Hi, just getting started with the tool, so I may have overlooked something!

From what I understand, we are meant to create our own config file and store the path as an environment variable for pier, right?

Would it be beneficial to have pier automatically generate a config file (and store it in /usr/bin or something) by default? Or is this against the vision/idea in some way?

**Comment by BenSchZA** [comment]
Hey @niniack! Thanks for checking in.

I think it would be useful to auto-generate a config file. The current behaviour is that Pier checks for a config file with the priority described below. I just noticed `$XDG_CONFIG_HOME` is not set on my machine, which means it would default to `$HOME/.pier.toml` in that case. 

I know @Plommonsorbet originally set the priorities up, and might have a better idea about where the best place to generate a config file would be. My suggestion would be `$HOME/.config/pier/pier.toml` - that seems to be pretty standard.

@niniack Would you like to attempt implementing this? If you're here as a user, that's totally fine too :+1: 

```
OPTIONS:
    -c, --config-file <path>    
            Sets a custom config file.
            
            DEFAULT PATH is otherwise determined in this order:
            
            - $PIER_CONFIG_PATH (environment variable if set)
            
            - pier.toml (in the current directory)
            
            - $XDG_CONFIG_HOME/pier/config.toml
            
            - $XDG_CONFIG_HOME/pier/config
            
            - $XDG_CONFIG_HOME/pier.toml
            
            - $HOME/.pier.toml
            
            - $HOME/.pier
            
             [env: PIER_CONFIG_PATH=]
```

**Comment by niniack** [comment]
Hey @BenSchZA. Thanks for the message.

Yeah, I'd like to give this a shot! Although, I'm absolutely new to Rust and may need a bit to get accustomed with the language and project. Otherwise, I'm quite excited to contribute. Frankly, I had been looking for a tool like this because I was getting frustrated trying to manage all my one-liners. Plus, I get to learn Rust! :) 

@Plommonsorbet Any pointers on how to get started or approach this would be awesome.

Thanks y'all!

**Comment by niniack** [comment]
So far I understand that if the config file path is not provided when running a command
- the `fallback_path()` function is called
- this loops through the priority path list defined in `default.rs` (also as you show above)
- if no file is found in any of the paths then a `NoConfigFile` error is raised which prints then exits the program

So, I suppose my question is: should this feature aim to handle the error by generating a config file? Or, should the config file generation be something a user does through a subcommand?

I'm leaning towards the latter because it seems to be a more transparent solution. Maybe the error message could point the user towards the subcommand for generating a config file?

Please feel free to correct me if I'm thinking in the wrong direction or have any incorrect assumptions!

**Comment by Plommonsorbet** [comment]
Hey

I'd be more than happy to help out! What time zone are you in @niniack ? Maybe we could jump on discord or something later? Otherwise I'll get back to you on your questions tonight after work!

**Comment by niniack** [comment]
Hey @Plommonsorbet 

I'm in UTC +5:30 (IST). Happy to chat on discord: myth-of-sissyfuss#7426.

Tbh no rush, whenever you get a chance is good really :+1: Thanks :)

**Comment by BenSchZA** [comment]
> Yeah, I'd like to give this a shot! Although, I'm absolutely new to Rust and may need a bit to get accustomed with the language and project. Otherwise, I'm quite excited to contribute. Frankly, I had been looking for a tool like this because I was getting frustrated trying to manage all my one-liners. Plus, I get to learn Rust! :)

We're all in the same boat here. I started this repo as a useful tool I thought I needed and to learn Rust, then @Plommonsorbet came on board and made some really big updates like much better testing and cleaned up the codebase, and then we moved it to `pier-cli` org. Great place to learn Rust :+1:

**Comment by Plommonsorbet** [comment]
> Hey @Plommonsorbet 
> 
> I'm in UTC +5:30 (IST). Happy to chat on discord: myth-of-sissyfuss#7426
> 
> Tbh no rush, whenever you get a chance is good really :+1: Thanks :) 
> 

I have time tonight if you're up for it / it's not too late. 

I'll be available from like 18.30(GMT+1) which seems like it's 23:00 your time.

**Comment by Plommonsorbet** [comment]
> > Yeah, I'd like to give this a shot! Although, I'm absolutely new to Rust and may need a bit to get accustomed with the language and project. Otherwise, I'm quite excited to contribute. Frankly, I had been looking for a tool like this because I was getting frustrated trying to manage all my one-liners. Plus, I get to learn Rust! :)
> 
> We're all in the same boat here. I started this repo as a useful tool I thought I needed and to learn Rust, then @Plommonsorbet came on board and made some really big updates like much better testing and cleaned up the codebase, and then we moved it to `pier-cli` org. Great place to learn Rust :+1: 

Exactly @BenSchZA , I think it's a great learning project. The concept is relatively simple and familiar which allows you to focus on learning the language rather than the problem you're trying to solve.

That's the reason i started contributing to it at least! :)

**Comment by niniack** [comment]
> > Hey @Plommonsorbet
> > I'm in UTC +5:30 (IST). Happy to chat on discord: myth-of-sissyfuss#7426
> > Tbh no rush, whenever you get a chance is good really +1 Thanks :)
> 
> I have time tonight if you're up for it / it's not too late.
> 
> I'll be available from like 18.30(GMT+1) which seems like it's 23:00 your time.

@Plommonsorbet Sounds good! I'll be around then

**Comment by niniack** [comment]
#60 Fixes this

**Comment by Plommonsorbet** [comment]
Sorry for the wait, been in full vacation mode for a lil bit. But it looks good and I've merged it now. :)
