### ISSUE TITLE
Allow use of `pier ls` as alias for `list`

### ISSUE THREAD

**Issue by BenSchZA** [pier-cli/pier#64]
I often find myself typing `pier ls` instead of `list` - probably because of being used to that with Docker, and the `ls` CLI tool. It should be fairly easy having two options for listing. Another thought was whether the default when running `pier` should be to list, as that's quite a common task? Feedback welcome! Maybe I'll take this on, haven't been active in a while.

**Comment by Plommonsorbet** [comment]
Hey Ben!

Sorry for getting back to you so late, been on vacation and decided to completely disconnect myself from tech during this time to recharge my batteries.

This alias already exists [here](https://github.com/pier-cli/pier/blob/master/src/cli.rs#L58) , you might be running an old version? I believe the cargo version is very out of date so if you installed via cargo that could be why. We should probably update in on cargo, you have the api token for cargo right?

If you would like to take a more active role again that would be very welcome! If you have any ideas of things you would like to do, hit me up on telegram and I would be more than happy to get you reaquainted with the code base! Would be nice to perhaps get som critique on the more opaque bits of the current code, I fear I may have gone a little too far into abstraction at points. :d

We could perhaps do a session discussing the future of pier? I'm sorta at a loss of what the future should be or what direction to take this project currently. It does seem like we have active users so perhaps we should try to up the seriousness of the project?Here's some suggestions I came up from a quick brainstorm: 
* more organized release structure?
* Automatic CI for pull requests?
* Automated cargo updates?
* Making the project more approchable?
* User survey?
* Refinding and restructuring the niche and use case?
* Document improvements?

Maybe this isn't the most related place to have this discussion, would be happy to move it to another issue or telegram or whatever suits you. :)
