### ISSUE TITLE
`cargo test` fails when ran in fish shell

### ISSUE THREAD

**Issue by abusch** [pier-cli/pier#67]
I tried to compile `pier` and one of the tests was failing. It turns out it depends on the user's current shell, which in my case is `fish`. Doing `SHELL="/bin/bash" cargo test` made them pass.

It makes sense that `pier` defaults to `$SHELL` to run scripts, but the tests probably shouldn't depend on the user's shell :)

**Comment by Plommonsorbet** [comment]
Hey,

Thanks for your issue.

While I do agree that the tests should not be dependent on the current shell, it is however really useful to use a posix shell to test some basic functionality.

I've added some shebangs to the tests that `run` scripts and tested it with
```
SHELL=$(which fish) cargo test
```

The testing code is pretty messy currently and is due for an overhaul when time permits.

Anyway thanks again for the issue! It was really helpful and had perfectly reproducible steps!
