### ISSUE TITLE
wrong tag with v1.5

### ISSUE THREAD

**Issue by chenrui333** [pier-cli/pier#93]
👋 looks like there is wrong tag with `v1.5`.

![image](https://github.com/pier-cli/pier/assets/1580956/3f17cb3a-51b6-418b-b9d1-21fa73aae341)

Also can you mark `v0.1.5` as latest release? Thanks!

**Comment by BenSchZA** [comment]
Thanks for pointing that out @chenrui333, I've updated the latest release and deleted the v1.5 tag.
